---
- hosts: localhost
  become: yes
  gather_facts: False

  vars_files:
  - vars/ansible.json

  tasks:
  - name: Ensure the list of dependencies is fulfilled
    pacman:
      name:
        - curl
        - ebtables
        - emacs-nox
        - fail2ban
        - firewalld
        - git
        - go
        - iproute
        - ipset
        - libpam-google-authenticator
        - proxychains-ng
        - qrencode
        - tmux
        - tor
        - torsocks
        - znc
        - znc-clientbuffer
      state: present
  - name: Ensure Freenode's network address is mapped to Tor's configuration
    lineinfile:
      path: /etc/tor/torrc
      line: 'mapaddress 10.99.99.90 ajnvpgl6prmkb7yktvue6im5wiedlz2w32uhcwaamdiecdrfpwwgnlqd.onion'
      insertbefore: EOF
  - name: Ensure OFTC's network address is mapped to Tor's configuration
    lineinfile:
      path: /etc/tor/torrc
      line: 'mapaddress 10.99.99.91 irc.oftc.net'
      insertbefore: EOF
  - name: Ensure all daemons are reloaded
    systemd:
      daemon_reload: yes
  - name: Ensure the Tor daemon is restared
    systemd:
      state: restarted
      daemon_reload: yes
      name: tor
  - name: Ensure the Tor daemon is enabled
    systemd:
      name: tor
      enabled: yes
