---
- name: Ensure the required packages are installed and current packages updated
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure the EPEL repository is enabled
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    - name: Ensure all packages are updated
      yum:
        name: '*'
        state: latest
    - name: Ensure the list of dependencies is installed
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - znc
          - znc-devel
          - tor
          - torsocks
          - emacs-nox
          - firewalld
          - tmux
          - curl
          - deltarpm
          - google-authenticator
          - qrencode
          - iproute
          - fail2ban
    - name: Install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present
- name: Ensure proxychains-ng is installed
  hosts: localhost
  become: yes
  tasks:
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive:
        src: https://github.com/rofl0r/proxychains-ng/archive/v4.14.zip
        dest: /tmp/proxychains-ng
        creates: /tmp/proxychains-ng/proxychains-ng-4.14
        remote_src: yes
