---
- name: Ensure the user bouncie is created with sudo access
  hosts: localhost
  become: yes
  user: ec2-user
  tasks:
    - name: Create the bouncie user
      user:
        name: bouncie
        shell: /bin/bash
    - name: Give sudo access to the bouncie user
      lineinfile:
        path: /etc/sudoers.d/bouncie
        line: 'bouncie  ALL=(ALL)   ALL'
        create: yes
- name: Ensure my public keys are added to the bouncie user
  hosts: localhost
  become: yes
  user: ec2-user
  tasks:
    - name: Create the SSH directory on bouncie's home folder
      authorized_key:
        user: bouncie
        state: present
        key: https://github.com/da-edra.keys
        path: /home/bouncie/.ssh/authorized_keys
- name: Ensure the bouncie user will set up a password on first login
  hosts: localhost
  become: yes
  user: ec2-user
  tasks:
    - name: Disable bouncie's password and expire it
      shell:
        cmd: passwd -d bouncie
    - name: Expire bouncie's password
      shell:
        cmd: passwd -e bouncie
